// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADDFauZ_fnLvYJXKe8sYD3szpfkXYK7vU',
    appId: '1:328682946260:web:6570c22f6c18580f20c541',
    messagingSenderId: '328682946260',
    projectId: 'orderprocessessingapp',
    authDomain: 'orderprocessessingapp.firebaseapp.com',
    storageBucket: 'orderprocessessingapp.appspot.com',
    measurementId: 'G-TPYG2GCMBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAwKteGH8Yh5EP-8KCTZxDrzzQQ0-xk0g',
    appId: '1:328682946260:android:cdc383bb78ccc3dc20c541',
    messagingSenderId: '328682946260',
    projectId: 'orderprocessessingapp',
    storageBucket: 'orderprocessessingapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNBiDvLO_4p4RMPekF4thOoJQYmRx5LWA',
    appId: '1:328682946260:ios:c5fb546d6f13303f20c541',
    messagingSenderId: '328682946260',
    projectId: 'orderprocessessingapp',
    storageBucket: 'orderprocessessingapp.appspot.com',
    iosClientId: '328682946260-r5sknpe2jnhotndud3s288qcb3cnhin2.apps.googleusercontent.com',
    iosBundleId: 'com.example.orderProcessesing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNBiDvLO_4p4RMPekF4thOoJQYmRx5LWA',
    appId: '1:328682946260:ios:76f9ed62751a18fe20c541',
    messagingSenderId: '328682946260',
    projectId: 'orderprocessessingapp',
    storageBucket: 'orderprocessessingapp.appspot.com',
    iosClientId: '328682946260-c4dut37954mc717kpbjbk6iajb6csc36.apps.googleusercontent.com',
    iosBundleId: 'com.example.orderProcessesing.RunnerTests',
  );
}
